### PR TITLE
Upgrade to PHP 8

### PR DESCRIPTION
**Pull request by vcampitelli**
- :arrow_up: Upgrading to PHP 8
- :arrow_up: Upgrading to PHPUnit 10
- :white_check_mark: Fixing tests due to some `Content-type` and `Transfer-encoding` inconsistencies
- :rotating_light: Applying PSR-12 coding style

### CODE REVIEW

**Comment by mooreds** [comment]
@vcampitelli are you aware that the FusionAuthClient.php file is generated from [this freemarker file](https://github.com/FusionAuth/fusionauth-client-builder/blob/master/src/main/client/php.client.ftl). So any formatting changes need to be made to that freemarker file, not to the file in this repository?

**Comment by mooreds** [comment]
Awesome, thanks!

**Comment by vcampitelli** [comment]
@mooreds / @tonyblank can we merge this so we can also close #31?

**Comment by tonyblank** [comment]
LGTM

**Pull request merged**
