### PR TITLE
Fix method header

### PR DESCRIPTION
**Pull request by TanguyGiton**
Fix method header causing issues when using withTenantId on FusionAuthClient.

### CODE REVIEW

**Comment by robotdan** [comment]
Thanks!

**Comment by robotdan** [comment]
`dev-master` is updated in packagist. https://packagist.org/packages/fusionauth/fusionauth-client

**Comment by TanguyGiton** [comment]
Great, thank you. Any idea when the next release will be out ?

**Comment by robotdan** [comment]
I pushed 1.13.3 with this fix. 
https://packagist.org/packages/fusionauth/fusionauth-client

**Pull request merged**
